---
abstract: 'Customize Multilevel Escalation from GUI Interface.'
author:
  - 'Basu Rohit <rohitbasu@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kernel-System-Escalation
requires:
  Encode: 0
  Encode::Locale: 0
  Getopt::Long: 0
  Pod::Usage: 0
  SOAP::Lite: 0
  perl: 5.008007
resources:
  bugtracker: https://github.com/basurohit77/Kernel-System-Escalation/issues
  homepage: https://github.com/basurohit77/Kernel-System-Escalation
  repository: https://github.com/basurohit77/Kernel-System-Escalation.git
version: 1.0.1
